# Generated by Django 3.0.4 on 2020-03-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('accomplishments', models.TextField(null=True)),
                ('platform', models.TextField(null=True)),
                ('foreign_policy', models.TextField(null=True)),
                ('unique', models.TextField(null=True, verbose_name='what sets this candidate apart')),
                ('is_active', models.BooleanField(default=True, verbose_name='is this candidate still in the race')),
                ('candidate_id', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(blank=True, editable=False, max_length=100)),
            ],
        ),
    ]
