# Generated by Django 3.0.2 on 2020-03-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='accomplishments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='platform',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_contributions',
            field=models.IntegerField(default=0, verbose_name='total independent contributions'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
