# Generated by Django 3.0.2 on 2020-03-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='unique',
            field=models.TextField(null=True, verbose_name='what sets this candidate apart'),
        ),
    ]
