# Generated by Django 3.0.2 on 2020-03-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_auto_20200305_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is this candidate still in the race'),
        ),
    ]
