# Generated by Django 3.0.2 on 2020-03-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='total_contributions',
        ),
    ]
