# Generated by Django 3.0.2 on 2020-03-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_auto_20200318_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
