# Generated by Django 3.0.2 on 2020-03-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_auto_20200324_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
